---

- name: Set up root access
  ansible.builtin.import_playbook: root_access.yaml

- name: Check Jetpack version
  ansible.builtin.import_playbook: ansible_check_jetpack.yaml  

- name: Set up extra drive
  ansible.builtin.import_playbook: ansible_setup_extra_drive.yaml

- name: Install and configure WES
  ansible.builtin.import_playbook: ansible_install_wes.yaml

