---
- name: Copy ROOTFS into the System
  hosts: root
  tasks:
    - name: Add the WaggleOS MOTD
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/update-motd.d/05-waggle"
        dest: /etc/update-motd.d/05-waggle
        mode: a+x

    - name: Configure the Network Interface, Udev Rules
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/udev/rules.d/10-waggle.rules"
        dest: /etc/udev/rules.d/10-waggle.rules

    - name: create the journal log folder if it does not exist
      ansible.builtin.file:
        path: /var/log/journal
        state: directory

    - name: Create journalctl config directory if it does not exist
      ansible.builtin.file:
        path: /etc/systemd/journald.conf.d
        state: directory

    - name: add the journalctl config to configure journalctl to save historical logs
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/journald.conf.d/10-waggle-journald.conf"
        dest: /etc/systemd/journald.conf.d/10-waggle-journald.conf

    - name: Configure Network Manager to Not Manage the k3s Networks
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/conf.d/cni.conf"
        dest: /etc/NetworkManager/conf.d/cni.conf

    - name: Set up k3s Shutdown Service
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/system/waggle-k3s-shutdown.service"
        dest: /etc/systemd/system/waggle-k3s-shutdown.service

    - name: Copy directory /ROOTFS/etc/waggle to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/waggle"
        dest: /etc

    - name: Set device name in /etc/waggle/config.ini
      ansible.builtin.copy:
        src: /etc/waggle/config.ini.agent.tmpl
        dest: /etc/waggle/config.ini

    - name: Configure the lan0 network interface to bind to 10.31.81.1
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/system-connections/lan"
        dest: /etc/NetworkManager/system-connections/lan
        mode: 0600

    - name: Configure the wan0 network interface
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/system-connections/wan"
        dest: /etc/NetworkManager/system-connections/wan
        mode: 0600

    - name: Configure the wifi network interface
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/system-connections/wifi"
        dest: /etc/NetworkManager/system-connections/wifi
        mode: 0600

    - name: Configure dnsmasq to create the device's internal 10.31.81.1/24 network (for use by kubernetes) by copying 10-waggle-base config file.
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/dnsmasq.d/10-waggle-base.conf"
        dest: /etc/dnsmasq.d/10-waggle-base.conf

    - name: Configure dnsmasq to create the device's internal 10.31.81.1/24 network by copying dnsmasq.service.d directory.
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/system/dnsmasq.service.d"
        dest: /etc/systemd/system

    - name: Set up k3s service override
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/system/k3s.service.d"
        dest: /etc/systemd/system

    - name: Setup the local docker registry mirrors (as the k3s config uses them)
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/system/waggle-registry-local.service"
        dest: /etc/systemd/system/waggle-registry-local.service

    - name: Add fallback DNS
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/systemd/resolved.conf.d/10-waggle-resolved.conf"
        dest: /etc/systemd/resolved.conf.d/10-waggle-resolved.conf

    - name: Add wifi dongle support by copying ROOTFS/etc/modprobe.d/rtl8821cu.conf to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/modprobe.d/rtl8821cu.conf"
        dest: /etc/modprobe.d/rtl8821cu.conf

    - name: Add wifi dongle support by copying ROOTFS/etc/modprobe.d/rtl8822bu.conf to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/modprobe.d/rtl8822bu.conf"
        dest: /etc/modprobe.d/rtl8822bu.conf

    - name: Add waggle hotspot support by copying ROOTFS/etc/NetworkManager/system-connections/wifi-waggle to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/system-connections/wifi-waggle"
        dest: /etc/NetworkManager/system-connections/wifi-waggle

    - name: Enable NetworkManager Connectivity checks by copying ROOTFS/etc/NetworkManager/conf.d/99-connectivity.conf to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/NetworkManager/conf.d/99-connectivity.conf"
        dest: /etc/NetworkManager/conf.d/99-connectivity.conf

    - name: Add ssh known hosts to system
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/ROOTFS/etc/ssh/ssh_known_hosts"
        dest: /etc/ssh/ssh_known_hosts

    - name: Reload Daemon
      ansible.builtin.systemd:
        daemon_reload: yes