name: "Build and Push Docker Images"

on:
  release:
    types: [published]
    paths:
      - "vm/**"
  pull_request:
    branches: ["main"]
    paths:
      - "vm/**"

jobs:
  push_to_registry:
    name: Build
    uses: waggle-sensor/.github/.github/workflows/build-and-push-docker-image.yml@main
    secrets: inherit
